# all paths have to be absolute
DATA:
  WORKSPACE_DIR:     "/workspaces/a2e/aupetit/pkg_SPLITREADER" # path to the workspace directory
  BAM_DIR:           "/workspaces/a2e/aupetit/pkg_SPLITREADER/BAMs" # path to the bam files
  REFERENCE:         "/workspaces/a2e/aupetit/pkg_SPLITREADER/Reference" # path to reference genome annotation files
  SCRIPT_DIR:        "/workspaces/a2e/aupetit/pkg_SPLITREADER/scripts_SPLITREADER" # location of SPLITREADER scripts
  TMP_DIR:           "/workspaces/a2e/aupetit/pkg_SPLITREADER/tmp" # path to the temporary directory
  GENOME:            "TAIR10" # Genome
  TE_LIB:            "TE_all_Athaliana" # name of the TE library
  TE_ANNOTATION:     "TAIR10_Quesneville_GFF3_transposons_only" # TE annotation file with no extension (.gff)
  BAMEXT:            ".sort" # extension of bam files
  COHORTNAME:        "TE_capture_accessions" # name of Cohort

PARAMS:
  DEPTH:                3 # Minimum number of reads (split+discordant)
  LS:                   200 # Library size
  MAXCOV:               100 # maximum negative coverage over insertion sites to remove regions with aberrant sequencing depth
  DPrefmin:             5 # minimum negative coverage over insertion sites required to be confident that an insertion is indeed absent (for the NEGATIVE_COVERAGE part)
  LENGTH:               150 # read length
  SNAKEMAKE_THREADS: 5            # number of threads for Snakemake ==> number of samples / SNAKEMAKE_THREADS = number of samples run at a time
  INTERNAL_THREADS:  5            # number of threads for the SPLITREADER ! Has to be inferior or equal to SNAKEMAKE_THREADS 

CHOICE:
  NEGATIVE_COVERAGE: True # Last filter of SPLITREADER
